import { useEffect, useState, type FormEvent } from 'react';
import { Modal } from '../../components/Modal';
import { PageHeader } from '../../components/PageHeader';
import { useAuth } from '../../contexts/AuthContext';
import { archiveGoal, createGoal, listGoalContributions, listGoals, recordGoalContribution, reverseGoalContribution, updateGoal } from '../../repositories/goalRepository';
import { listSpaces } from '../../repositories/spaceRepository';
import type { GoalContribution, SavingsGoal, Space } from '../../types/models';
import { getErrorMessage } from '../../utils/errors';
import { formatMoney, toMinorUnits } from '../../utils/money';

function today() { return new Date().toISOString().slice(0, 10); }
export function GoalsPage() {
  const { user, profile } = useAuth();
  const [goals, setGoals] = useState<SavingsGoal[]>([]); const [spaces, setSpaces] = useState<Space[]>([]); const [contributions, setContributions] = useState<GoalContribution[]>([]);
  const [editing, setEditing] = useState<SavingsGoal | null>(null); const [contributing, setContributing] = useState<SavingsGoal | null>(null); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const load = async () => { if (!user) return; setError(''); try { const [g,s,c] = await Promise.all([listGoals(user.uid), listSpaces(user.uid), listGoalContributions(user.uid)]); setGoals(g); setSpaces(s.filter((item) => !item.archivedAt)); setContributions(c); } catch (e) { setError(getErrorMessage(e)); } };
  useEffect(() => { void load(); }, [user]);
  const target = goals.reduce((sum,item)=>sum+item.targetMinor,0); const saved = goals.reduce((sum,item)=>sum+item.currentMinor,0);
  return <main className="page"><PageHeader eyebrow="Planning" title="Savings goals" description="Track money you plan to save for emergencies, school, travel, equipment, or anything else." action={<button className="button primary" onClick={()=>{setEditing(null);setShowForm(true);}}>Add savings goal</button>} />
    {error && <div className="notice error">{error}</div>}<section className="summary-grid"><article className="summary-card featured"><span>Total needed</span><strong>{formatMoney(target,profile?.currency||'BND')}</strong><small>Across current goals</small></article><article className="summary-card"><span>Saved so far</span><strong>{formatMoney(saved,profile?.currency||'BND')}</strong><small>Progress you entered</small></article><article className="summary-card"><span>Still needed</span><strong>{formatMoney(target-saved,profile?.currency||'BND')}</strong><small>To finish all goals</small></article><article className="summary-card"><span>Finished</span><strong>{goals.filter((g)=>g.status==='completed').length}</strong><small>Goals finished</small></article></section>
    <section className="planning-card-grid">{goals.map((goal)=>{const ratio=goal.targetMinor?Math.min(100,Math.round(goal.currentMinor/goal.targetMinor*100)):0; const recent=contributions.filter((c)=>c.goalId===goal.id).slice(0,3); return <article className="planning-card goal-card" key={goal.id}><div className="planning-card-head"><div><span className="eyebrow">{goal.status === 'completed' ? 'Finished' : 'In progress'}</span><h3>{goal.name}</h3></div><strong>{ratio}%</strong></div><div className="budget-amount-line"><strong>{formatMoney(goal.currentMinor,goal.currency)}</strong><span>of {formatMoney(goal.targetMinor,goal.currency)}</span></div><div className="progress planning-progress"><span style={{width:`${ratio}%`}}/></div><div className="planning-meta"><span>{spaces.find((s)=>s.id===goal.spaceId)?.name||'Space'}</span><span>{goal.targetDate?`Aim to finish by ${goal.targetDate}`:'No deadline'}</span></div>{recent.length>0&&<div className="mini-history">{recent.map((item)=><div key={item.id}><span>{item.contributionDate}</span><strong>{item.reversalOf?'-':''}{formatMoney(item.amountMinor,item.currency)}</strong>{item.status==='posted'&&!item.reversalOf&&<button className="text-button danger" onClick={async()=>{if(confirm('Undo this saved progress?')){await reverseGoalContribution(item.id);await load();}}}>Undo</button>}</div>)}</div>}<div className="button-row"><button className="button primary" disabled={goal.status==='completed'} onClick={()=>setContributing(goal)}>Add progress</button><button className="button secondary" onClick={()=>{setEditing(goal);setShowForm(true);}}>Edit</button><button className="text-button danger" onClick={async()=>{if(confirm(`Hide ${goal.name}?`)){await archiveGoal(goal.id);await load();}}}>Hide</button></div></article>;})}</section>
    {showForm&&<Modal title={editing?'Edit goal':'Add savings goal'} onClose={()=>setShowForm(false)}><GoalForm goal={editing} spaces={spaces} onSaved={async()=>{setShowForm(false);await load();}}/></Modal>}
    {contributing&&<Modal title={`Add progress to ${contributing.name}`} onClose={()=>setContributing(null)}><ContributionForm goal={contributing} onSaved={async()=>{setContributing(null);await load();}}/></Modal>}
  </main>;
}
function GoalForm({goal,spaces,onSaved}:{goal:SavingsGoal|null;spaces:Space[];onSaved:()=>Promise<void>}){const[name,setName]=useState(goal?.name||'');const[spaceId,setSpaceId]=useState(goal?.spaceId||spaces[0]?.id||'');const[target,setTarget]=useState(goal?String(goal.targetMinor/100):'');const[targetDate,setTargetDate]=useState(goal?.targetDate||'');const[note,setNote]=useState(goal?.note||'');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const targetMinor=toMinorUnits(target);if(targetMinor<=0)throw new Error('Enter a target greater than BND 0.00.');if(goal)await updateGoal({goalId:goal.id,name,targetMinor,targetDate:targetDate||undefined,note});else await createGoal({name,spaceId,targetMinor,targetDate:targetDate||undefined,note});await onSaved();}catch(x){setError(getErrorMessage(x));}finally{setBusy(false);}};return <form className="form-stack" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<label>Goal name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><div className="form-grid"><label>Space<select value={spaceId} onChange={e=>setSpaceId(e.target.value)} disabled={Boolean(goal)}>{spaces.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Amount needed (BND)<input value={target} onChange={e=>setTarget(e.target.value)} inputMode="decimal" required/></label><label className="span-2">Finish by<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label></div><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save goal'}</button></form>}
function ContributionForm({goal,onSaved}:{goal:SavingsGoal;onSaved:()=>Promise<void>}){const[amount,setAmount]=useState('');const[date,setDate]=useState(today());const[note,setNote]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const amountMinor=toMinorUnits(amount);if(amountMinor<=0)throw new Error('Enter an amount greater than BND 0.00.');await recordGoalContribution({goalId:goal.id,amountMinor,contributionDate:date,note});await onSaved();}catch(x){setError(getErrorMessage(x));}finally{setBusy(false);}};return <form className="form-stack" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<div className="notice">This only updates your savings goal. It does not take money out of an account.</div><label>Amount (BND)<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save progress'}</button></form>}
