import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Modal } from '../../components/Modal';
import { PageHeader } from '../../components/PageHeader';
import { useAuth } from '../../contexts/AuthContext';
import { DEFAULT_TRANSACTION_CATEGORIES, categoryIconGlyph } from '../categories/defaultCategories';
import { listAccounts } from '../../repositories/accountRepository';
import { listCustomCategories } from '../../repositories/categoryRepository';
import { archiveCommitment, createCommitment, listCommitments, listCommitmentPayments, payCommitment, updateCommitment } from '../../repositories/commitmentRepository';
import { listSpaces } from '../../repositories/spaceRepository';
import type { Account, Commitment, CommitmentFrequency, CommitmentPayment, CommitmentType, Space, TransactionCategory } from '../../types/models';
import { getErrorMessage } from '../../utils/errors';
import { formatMoney, toMinorUnits } from '../../utils/money';

function today() { return new Date().toISOString().slice(0, 10); }
const dueLabels = { completed: 'Finished', overdue: 'Overdue', due: 'Due today', upcoming: 'Coming up' } as const;
const frequencyLabels: Record<CommitmentFrequency, string> = { once: 'One time', weekly: 'Weekly', monthly: 'Monthly', quarterly: 'Every 3 months', yearly: 'Yearly' };

function dueState(item: Commitment): 'completed' | 'overdue' | 'due' | 'upcoming' {
  if (item.status === 'completed') return 'completed';
  const due = item.nextDueDate || item.startDate;
  const now = today();
  if (due < now) return 'overdue';
  if (due === now) return 'due';
  return 'upcoming';
}

export function CommitmentsPage() {
  const { user, profile } = useAuth();
  const [items, setItems] = useState<Commitment[]>([]); const [payments,setPayments]=useState<CommitmentPayment[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [spaces,setSpaces]=useState<Space[]>([]); const [categories,setCategories]=useState<TransactionCategory[]>([]);
  const [editing,setEditing]=useState<Commitment|null>(null); const [paying,setPaying]=useState<Commitment|null>(null); const [showForm,setShowForm]=useState(false); const [typeFilter,setTypeFilter]=useState<'all'|CommitmentType>('all'); const [error,setError]=useState('');
  const load=async()=>{if(!user)return;setError('');try{const[c,p,a,s,custom]=await Promise.all([listCommitments(user.uid),listCommitmentPayments(user.uid),listAccounts(user.uid),listSpaces(user.uid),listCustomCategories(user.uid)]);setItems(c);setPayments(p);setAccounts(a);setSpaces(s.filter(x=>!x.archivedAt));setCategories([...DEFAULT_TRANSACTION_CATEGORIES.filter(x=>x.kind==='expense'),...custom.filter(x=>x.kind==='expense'&&!x.archivedAt)]);}catch(e){setError(getErrorMessage(e));}};
  useEffect(()=>{void load();},[user]);
  const visible=items.filter(i=>typeFilter==='all'||i.type===typeFilter); const upcoming=items.filter(i=>dueState(i)==='upcoming'||dueState(i)==='due').length; const overdue=items.filter(i=>dueState(i)==='overdue').length; const outstanding=items.reduce((sum,i)=>sum+(i.type==='instalment'&&i.totalAmountMinor?Math.max(0,i.totalAmountMinor-i.amountPaidMinor):i.status==='active'?i.amountMinor:0),0);
  const accountMap=useMemo(()=>new Map(accounts.map(i=>[i.id,i])),[accounts]);
  return <main className="page"><PageHeader eyebrow="Planning" title="Bills & instalments" description="Track bills and instalments, then record payments from the account you used." action={<button className="button primary" onClick={()=>{setEditing(null);setShowForm(true);}}>Add bill or instalment</button>}/>{error&&<div className="notice error">{error}</div>}
    <section className="summary-grid"><article className="summary-card featured"><span>Still to pay</span><strong>{formatMoney(outstanding,profile?.currency||'BND')}</strong><small>Instalments and upcoming bills</small></article><article className="summary-card"><span>Coming up</span><strong>{upcoming}</strong><small>Due today or later</small></article><article className="summary-card"><span>Overdue</span><strong>{overdue}</strong><small>Needs attention</small></article><article className="summary-card"><span>Finished</span><strong>{items.filter(i=>i.status==='completed').length}</strong><small>Paid bills and instalments</small></article></section>
    <div className="segmented-control planning-filter"><button className={typeFilter==='all'?'active':''} onClick={()=>setTypeFilter('all')}>All</button><button className={typeFilter==='bill'?'active':''} onClick={()=>setTypeFilter('bill')}>Bills</button><button className={typeFilter==='instalment'?'active':''} onClick={()=>setTypeFilter('instalment')}>Instalments</button></div>
    <section className="planning-card-grid">{visible.map(item=>{const state=dueState(item);const remaining=item.totalAmountMinor?Math.max(0,item.totalAmountMinor-item.amountPaidMinor):0;const ratio=item.totalAmountMinor?Math.min(100,Math.round(item.amountPaidMinor/item.totalAmountMinor*100)):item.status==='completed'?100:0;const recent=payments.filter(p=>p.commitmentId===item.id).slice(0,2);return <article className={`planning-card commitment-card state-${state}`} key={item.id}><div className="planning-card-head"><div><span className="eyebrow">{dueLabels[state]}</span><h3>{item.name}</h3></div><span className="type-badge">{item.type === 'bill' ? 'Bill' : 'Instalment'}</span></div><div className="budget-amount-line"><span>{item.type==='bill'?'Amount due each cycle':'Instalment amount per cycle'}</span><strong>{formatMoney(item.amountMinor,item.currency)}</strong><span>{frequencyLabels[item.frequency]}</span></div>{item.type==='instalment'&&<><div className="progress planning-progress"><span style={{width:`${ratio}%`}}/></div><div className="planning-meta"><span>Paid {formatMoney(item.amountPaidMinor,item.currency)}</span><span>Left {formatMoney(remaining,item.currency)}</span></div></>}<div className="planning-meta"><span>{item.payee||item.categoryName}</span><span>{item.nextDueDate?`Due ${item.nextDueDate}`:'Finished'}</span></div><div className="planning-meta"><span>{accountMap.get(item.accountId||'')?.name||'Choose an account when you pay'}</span><span>Remind me {item.reminderDays} day(s)</span></div>{recent.length>0&&<div className="mini-history">{recent.map(p=><div key={p.id}><span>{p.paymentDate}</span><strong>{formatMoney(p.amountMinor,p.currency)}</strong><span>{p.status === 'posted' ? 'Saved' : 'Undone'}</span></div>)}</div>}<div className="button-row"><button className="button primary" disabled={item.status==='completed'} onClick={()=>setPaying(item)}>Add payment</button><button className="button secondary" onClick={()=>{setEditing(item);setShowForm(true);}}>Edit</button><button className="text-button danger" onClick={async()=>{if(confirm(`Hide ${item.name}?`)){await archiveCommitment(item.id);await load();}}}>Hide</button></div></article>})}</section>
    {showForm&&<Modal title={editing?'Edit bill or instalment':'Add bill or instalment'} onClose={()=>setShowForm(false)}><CommitmentForm item={editing} accounts={accounts} spaces={spaces} categories={categories} onSaved={async()=>{setShowForm(false);await load();}}/></Modal>}
    {paying&&<Modal title={`Pay ${paying.name}`} onClose={()=>setPaying(null)}><PaymentForm item={paying} accounts={accounts} onSaved={async()=>{setPaying(null);await load();}}/></Modal>}
  </main>;
}

function CommitmentForm({item,accounts,spaces,categories,onSaved}:{item:Commitment|null;accounts:Account[];spaces:Space[];categories:TransactionCategory[];onSaved:()=>Promise<void>}){
  const[type,setType]=useState<CommitmentType>(item?.type||'bill');const[name,setName]=useState(item?.name||'');const[payee,setPayee]=useState(item?.payee||'');const[spaceId,setSpaceId]=useState(item?.spaceId||spaces[0]?.id||'');const[accountId,setAccountId]=useState(item?.accountId||'');const[categoryId,setCategoryId]=useState(item?.categoryId||'expense-utilities');const[amount,setAmount]=useState(item?String(item.amountMinor/100):'');const[total,setTotal]=useState(item?.totalAmountMinor?String(item.totalAmountMinor/100):'');const[frequency,setFrequency]=useState<CommitmentFrequency>(item?.frequency||'monthly');const[dueDate,setDueDate]=useState(item?.nextDueDate||item?.startDate||today());const[endDate,setEndDate]=useState(item?.endDate||'');const[reminderDays,setReminderDays]=useState(String(item?.reminderDays??3));const[note,setNote]=useState(item?.note||'');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const selectedSpace=spaces.find(s=>s.id===spaceId);const scope=selectedSpace?.type==='sme'?'business':'personal';const scopedCategories=categories.filter(c=>c.scope==='both'||c.scope===scope);const scopedAccounts=accounts.filter(a=>a.currency===selectedSpace?.currency);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const amountMinor=toMinorUnits(amount);if(amountMinor<=0)throw new Error('Enter an amount greater than BND 0.00.');const totalAmountMinor=type==='instalment'?toMinorUnits(total):undefined;if(type==='instalment'&&(!totalAmountMinor||totalAmountMinor<amountMinor))throw new Error('The full instalment total must be the same as or more than one payment.');const base={name,payee:payee||undefined,accountId:accountId||undefined,categoryId,amountMinor,totalAmountMinor,frequency,nextDueDate:dueDate,endDate:endDate||undefined,reminderDays:Number(reminderDays),note};if(item)await updateCommitment({commitmentId:item.id,...base});else await createCommitment({type,spaceId,startDate:dueDate,...base});await onSaved();}catch(x){setError(getErrorMessage(x));}finally{setBusy(false);}};
  return <form className="form-stack" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<div className="form-grid"><label>Type<select value={type} onChange={e=>setType(e.target.value as CommitmentType)} disabled={Boolean(item)}><option value="bill">Bill</option><option value="instalment">Instalment</option></select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Paid to<input value={payee} onChange={e=>setPayee(e.target.value)} placeholder="DST, landlord, supplier"/></label><label>Space<select value={spaceId} onChange={e=>{setSpaceId(e.target.value);setCategoryId('');setAccountId('');}} disabled={Boolean(item)}>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Usual account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Choose when paying</option>{scopedAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Spending category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)} required>{scopedCategories.map(c=><option key={c.id} value={c.id}>{categoryIconGlyph(c.icon)} {c.name}</option>)}</select></label>{type==='bill'?<label>Amount due each cycle (BND)<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/><small>The amount you normally pay each time this bill is due.</small></label>:<><label>Full instalment total (BND)<input value={total} onChange={e=>setTotal(e.target.value)} inputMode="decimal" required/><small>The full amount you need to pay from start to finish.</small></label><label>Instalment amount per cycle (BND)<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/><small>The amount you normally pay each time.</small></label></>}<label>How often<select value={frequency} onChange={e=>setFrequency(e.target.value as CommitmentFrequency)}><option value="once">One time</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Every 3 months</option><option value="yearly">Yearly</option></select></label><label>Next due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/></label><label>End date<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>Remind me this many days early<input type="number" min="0" max="60" value={reminderDays} onChange={e=>setReminderDays(e.target.value)}/></label></div><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save bill or instalment'}</button></form>
}
function PaymentForm({item,accounts,onSaved}:{item:Commitment;accounts:Account[];onSaved:()=>Promise<void>}){const[accountId,setAccountId]=useState(item.accountId||accounts[0]?.id||'');const[amount,setAmount]=useState(String((item.type==='instalment'&&item.totalAmountMinor?Math.min(item.amountMinor,item.totalAmountMinor-item.amountPaidMinor):item.amountMinor)/100));const[date,setDate]=useState(today());const[note,setNote]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const available=accounts.filter(a=>a.currency===item.currency);const parsedAmountMinor=useMemo(()=>{try{return Math.max(0,toMinorUnits(amount));}catch{return 0;}},[amount]);const remainingBefore=item.type==='instalment'&&item.totalAmountMinor?Math.max(0,item.totalAmountMinor-item.amountPaidMinor):0;const remainingAfter=Math.max(0,remainingBefore-parsedAmountMinor);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const amountMinor=toMinorUnits(amount);if(amountMinor<=0)throw new Error('Enter a payment greater than BND 0.00.');await payCommitment({commitmentId:item.id,accountId,amountMinor,paymentDate:date,note});await onSaved();}catch(x){setError(getErrorMessage(x));}finally{setBusy(false);}};return <form className="form-stack" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<div className="notice">This saves a payment and updates the selected account balance once.</div><label>Account used<select value={accountId} onChange={e=>setAccountId(e.target.value)} required>{available.map(a=><option value={a.id} key={a.id}>{a.name} — {formatMoney(a.ledgerBalanceMinor,a.currency)}</option>)}</select></label><label>Amount paid now (BND)<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/><small>The amount you are paying now.</small></label>{item.type==='instalment'&&item.totalAmountMinor&&<div className="transaction-preview"><div><span>Amount left before payment</span><strong>{formatMoney(remainingBefore,item.currency)}</strong></div><div><span>Amount left after payment</span><strong>{formatMoney(remainingAfter,item.currency)}</strong></div><small>The amount left cannot go below BND 0.00.</small></div>}<label>Payment date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><button className="button primary full" disabled={busy}>{busy?'Saving…':'Save payment'}</button></form>}
