import { useEffect, useState, type FormEvent } from 'react';
import { EmptyState } from '../../components/EmptyState';
import { Modal } from '../../components/Modal';
import { PageHeader } from '../../components/PageHeader';
import { useAuth } from '../../contexts/AuthContext';
import { archiveAccount, createAccount, listAccounts, updateAccount } from '../../repositories/accountRepository';
import type { Account, AccountClassification, AccountType } from '../../types/models';
import { getErrorMessage } from '../../utils/errors';
import { formatMoney, toMinorUnits } from '../../utils/money';

const accountLabels: Record<AccountType, string> = { bank: 'Bank', cash: 'Cash', e_wallet: 'E-wallet', credit_card: 'Credit card' };

export function AccountsPage() {
  const { user, profile } = useAuth();
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [modal, setModal] = useState<'create' | 'edit' | null>(null);
  const [selected, setSelected] = useState<Account | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { if (!user) return; setLoading(true); try { setAccounts(await listAccounts(user.uid)); } catch (e) { setError(getErrorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [user]);
  const total = accounts.filter((a) => a.type !== 'credit_card').reduce((sum, a) => sum + a.ledgerBalanceMinor, 0);

  return <main className="page"><PageHeader eyebrow="Money sources" title="Accounts" description="Accounts are independent. Transactions will connect them to Spaces." action={<button className="button primary" onClick={() => setModal('create')}>+ Add account</button>} />{error && <div className="notice error">{error}</div>}<section className="account-summary"><div><span>Total non-credit balance</span><strong>{formatMoney(total, profile?.currency || 'BND')}</strong></div><div><span>Active accounts</span><strong>{accounts.length}</strong></div><div><span>Balance method</span><strong>Posted ledger</strong></div></section><div className="info-banner"><strong>Protected posting</strong><span>Opening balances are posted by a Cloud Function with an idempotency key. The browser cannot write accounts or ledger entries directly.</span></div>{loading ? <div className="loading-panel">Loading Accounts…</div> : accounts.length === 0 ? <EmptyState title="Add your first account" description="Start with BIBD, Baiduri, Cash, an e-wallet, or a credit card." action={<button className="button primary" onClick={() => setModal('create')}>Add account</button>} /> : <section className="account-list">{accounts.map((account) => <article className="account-card" key={account.id}><span className={`account-symbol large ${account.type}`}>{account.name.charAt(0)}</span><div className="account-main"><div><h2>{account.name}</h2><p>{account.institution || accountLabels[account.type]} · {account.classification}</p></div><small>{account.displayId}</small></div><div className="account-balance"><span>Ledger balance</span><strong>{formatMoney(account.ledgerBalanceMinor, account.currency)}</strong><small>Opening: {formatMoney(account.openingBalanceMinor, account.currency)}</small></div><div className="account-actions"><button className="text-button" onClick={() => { setSelected(account); setModal('edit'); }}>Edit</button><button className="text-button danger" onClick={() => void archiveAccount(account.id).then(load)}>Archive</button></div></article>)}</section>}{modal === 'create' && profile && <AccountForm currency={profile.currency} onClose={() => setModal(null)} onSubmit={async (values) => { await createAccount(values); setModal(null); await load(); }} />}{modal === 'edit' && selected && <AccountForm currency={selected.currency} initial={selected} onClose={() => setModal(null)} onSubmit={async (values) => { await updateAccount({ accountId: selected.id, name: values.name, institution: values.institution, type: values.type, classification: values.classification }); setModal(null); await load(); }} />}</main>;
}

function AccountForm({ currency, initial, onClose, onSubmit }: { currency: string; initial?: Account; onClose: () => void; onSubmit: (values: { name: string; institution?: string; type: AccountType; classification: AccountClassification; currency: string; openingBalanceMinor: number }) => Promise<void> }) {
  const [name, setName] = useState(initial?.name || ''); const [institution, setInstitution] = useState(initial?.institution || ''); const [type, setType] = useState<AccountType>(initial?.type || 'bank'); const [classification, setClassification] = useState<AccountClassification>(initial?.classification || 'personal'); const [opening, setOpening] = useState(initial ? String(initial.openingBalanceMinor / 100) : '0.00'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await onSubmit({ name, institution, type, classification, currency, openingBalanceMinor: initial ? initial.openingBalanceMinor : toMinorUnits(opening) }); } catch (e) { setError(getErrorMessage(e)); } finally { setBusy(false); } };
  return <Modal title={initial ? 'Edit account' : 'Add account'} onClose={onClose}><form className="form-grid" onSubmit={submit}>{error && <div className="notice error span-2">{error}</div>}<label className="span-2">Account name<input required value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. BIBD Main" /></label><label>Type<select value={type} onChange={(e) => setType(e.target.value as AccountType)}><option value="bank">Bank</option><option value="cash">Cash</option><option value="e_wallet">E-wallet</option><option value="credit_card">Credit card</option></select></label><label>Classification<select value={classification} onChange={(e) => setClassification(e.target.value as AccountClassification)}><option value="personal">Personal</option><option value="business">Business</option></select></label><label className="span-2">Institution or provider<input value={institution} onChange={(e) => setInstitution(e.target.value)} placeholder="BIBD, Baiduri, Cash Wallet…" /></label><label className="span-2">Opening balance ({currency})<input disabled={Boolean(initial)} inputMode="decimal" value={opening} onChange={(e) => setOpening(e.target.value)} />{initial && <small>Opening balances cannot be silently edited. A correction will use a posted adjustment in the transaction phase.</small>}</label><div className="modal-actions span-2"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : initial ? 'Save changes' : 'Create and post opening balance'}</button></div></form></Modal>;
}
